title: "Environment"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# URL
baseurl: "/vetiveria.github.io"
url: "https://vetiveria.github.io/"

# LaTeX math equation support
use_math: true

# kramdown
kramdown:
  math_engine: mathjax
